pipeline {
    agent {
        node 'docker'
    }
    parameters {
        string(name: 'IMAGE_BUILD_NUMBER')
    }
    stages {
        stage('Fetch the docker image'){
            steps {
                copyArtifacts(
                    projectName: '/dir_manager/build_docker_image_pipeline',
                    selector: params.IMAGE_BUILD_NUMBER ? specific(params.IMAGE_BUILD_NUMBER) : lastSuccessful()
                )
            }
        }
        stage('load the docker image'){
            steps {
                sh 'ls'
                sh 'docker load < cloudify*.tar'
            }
        }
        stage('install the inte-tests package') {
            steps {
                sh '''
                    virtualenv venv
                    venv/bin/pip install https://github.com/cloudify-cosmo/cloudify-common/archive/master.zip
                    venv/bin/pip install https://github.com/cloudify-cosmo/cloudify-cli/archive/master.zip
                    venv/bin/pip install rest-service/
                    venv/bin/pip install tests/
                '''
            }
        }
        stage('run tests'){
            steps {
                sh 'pytest tests/ --collect-only'
            }
            post {
                cleanup {
                    cleanWs()
                }
            }
        }
    }
}