"""empty message

Revision ID: b1560f22b5d1
Revises: 1fbd6bf39e84
Create Date: 2019-02-18 14:07:44.382551

"""
from alembic import op
import sqlalchemy as sa
import manager_rest

# revision identifiers, used by Alembic.
revision = 'b1560f22b5d1'
down_revision = '1fbd6bf39e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rabbitmq_brokers',
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('params', manager_rest.storage.models_base.JSONString(),
                  nullable=False),
        sa.PrimaryKeyConstraint('name', name=op.f('rabbitmq_brokers_pkey'))
    )
    op.create_table(
        'certificates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('updated_at', manager_rest.storage.models_base.UTCDateTime(),
                  nullable=True),
        sa.Column('_updater_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['_updater_id'], [u'users.id'],
                                name=op.f('certificates__updater_id_fkey'),
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'name', name=op.f('certificates_pkey'))
    )
    op.create_table(
        'config',
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('value', manager_rest.storage.models_base.JSONString(),
                  nullable=False),
        sa.Column('updated_at', manager_rest.storage.models_base.UTCDateTime(),
                  nullable=True),
        sa.Column('_updater_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['_updater_id'], [u'users.id'],
                                name=op.f('config__updater_id_fkey'),
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('name', name=op.f('config_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    op.drop_table('certificates')
    op.drop_table('rabbitmq_brokers')
    # ### end Alembic commands ###
